# This is a basic workflow to help you get started with Actions

name: Build stage

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the master branch
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          npm install
      - name: Check Code Quality
        run: |
          npm run lint
      - name: Build
        run: |
          npm run build
      - name: Unit Tests
        run: |
          echo "todo"
